name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install DevTools CLI
      - name: Install DevTools
        run: curl -fsSL https://raw.githubusercontent.com/the-dev-tools/dev-tools/main/apps/cli/install.sh | bash

      # Run a test flow and export JUnit results
      - name: Run DevTools Flow
        run: devtools flow run --report junit:results.xml test.yaml

      # Upload results.xml as artifact
      - name: Upload JUnit Report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: results.xml

      # (Optional) Parse JUnit results so they show in GitHub UI
      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: results.xml
