name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write   # ✅ allow junit-report action to create checks

    env:
      LOGIN_EMAIL: ${{ secrets.MY_EMAIL }}
      LOGIN_PASSWORD: ${{ secrets.MY_PASSWORD }}
      
    steps:
      - uses: actions/checkout@v4

      # Install DevTools CLI
      - name: Install DevTools
        run: curl -fsSL https://raw.githubusercontent.com/the-dev-tools/dev-tools/main/apps/cli/install.sh | bash

      # Run a test flow and export JUnit results
      - name: Run DevTools Flow
        run: devtools flow run --report console --report junit:results.xml test.yaml

      # Upload results.xml as artifact
      - name: Upload JUnit Report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: results.xml

      # Publish JUnit results in GitHub UI
      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: results.xml
          include_passed: true   # ✅ show passed tests in the summary
